# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0JLndk8lHaG5Ml6dJWRJWklkYqaPDfZ
"""

# تثبيت مكتبة Transformers و Datasets من Hugging Face
# وتثبيت مكتبة Arabert المخصصة لمعالجة النصوص العربية
!pip install transformers[torch] datasets arabert farasa pyarabic

from datasets import Dataset
import pandas as pd

# إنشاء مجموعة بيانات مكثفة تغطي الفئات الأربع (سياسة، اقتصاد، رياضة، طقس)
news_data = {
    "text": [
        # --- اقتصاد ---
        "ارتفاع مؤشرات البورصة اليوم بفضل أسهم قطاع البنوك",
        "تراجع سعر صرف العملة المحلية أمام الدولار في التداولات الصباحية",
        "البنك المركزي يرفع أسعار الفائدة للحد من معدلات التضخم",
        "اتفاقية تجارية جديدة بين الصين والولايات المتحدة لتعزيز الصادرات",
        "انخفاض أسعار النفط عالمياً بعد زيادة المخزون الأمريكي",

        # --- رياضة ---
        "النادي الأهلي يتوج بلقب الدوري بعد فوزه في المباراة الأخيرة",
        "المنتخب الوطني يستعد لتصفيات كأس العالم بمعسكر مغلق",
        "إصابة نجم خط الوسط ستبعده عن الملاعب لمدة ثلاثة أسابيع",
        "انطلاق منافسات البطولة العربية للتنس في القاهرة بمشاركة واسعة",
        "نتائج قرعة دوري أبطال أوروبا تسفر عن مواجهات قوية",

        # --- سياسة ---
        "وزير الخارجية يلتقي بنظيره الفرنسي لمناقشة الأزمات الإقليمية",
        "البرلمان يصوت بالأغلبية على قانون الانتخابات الجديد",
        "قمة دولية في بروكسل لبحث ملف التغير المناخي والأمن الدولي",
        "الإعلان عن تشكيل حكومة ائتلافية جديدة لإنهاء الأزمة السياسية",
        "الرئيس يفتتح عدداً من المشاريع القومية في العاصمة",

        # --- طقس ---
        "تحذيرات من عاصفة رملية تضرب المناطق الصحراوية غداً",
        "هطول أمطار غزيرة تسبب في عرقلة حركة السير بوسط المدينة",
        "درجات الحرارة تتخطى الأربعين في موجة حر تستمر لثلاثة أيام",
        "الأرصاد الجوية تتوقع تساقط الثلوج على المرتفعات الجبلية",
        "استقرار في حالة الطقس وهدوء في سرعة الرياح على كافة الأنحاء"
    ],
    # التسميات (Labels): 0=سياسة، 1=اقتصاد، 2=رياضة، 3=طقس
    "label": [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3]
}

# تحويل البيانات إلى تنسيق Datasets الخاص بـ Hugging Face
df = pd.DataFrame(news_data)
dataset = Dataset.from_pandas(df)

# تقسيم البيانات إلى تدريب واختبار (لضمان الدقة لاحقاً)
dataset = dataset.train_test_split(test_size=0.2)
train_dataset = dataset["train"]
test_dataset = dataset["test"]

print(f"تم تجهيز {len(train_dataset)} جملة للتدريب و {len(test_dataset)} جملة للاختبار.")

from transformers import AutoTokenizer
from arabert.preprocess import ArabertPreprocessor

model_name = "aubmindlab/bert-base-arabertv02"
tokenizer = AutoTokenizer.from_pretrained(model_name)
prep_object = ArabertPreprocessor(model_name=model_name)

def preprocess_function(examples):
    # تنظيف النص العربي أولاً باستخدام ArabertPreprocessor
    cleaned_texts = [prep_object.preprocess(t) for t in examples["text"]]
    # تحويل النصوص إلى أرقام (Tokens)
    return tokenizer(cleaned_texts, padding="max_length", truncation=True, max_length=128)

tokenized_datasets = dataset.map(preprocess_function, batched=True)
print("تمت عملية المعالجة والتقطيع بنجاح!")

from transformers import AutoModelForSequenceClassification

# تحميل نموذج BERT العربي مع تحديد عدد الفئات (4)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=4)

print("تم تحميل نموذج AraBERT بنجاح.")

import torch

def predict(text):
    text_preprocessed = prep_object.preprocess(text)
    inputs = tokenizer(text_preprocessed, return_tensors="pt", padding=True, truncation=True, max_length=128)

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    target_class = torch.argmax(probs).item()

    labels = ["سياسة", "اقتصاد", "رياضة", "طقس"]
    return labels[target_class]

# جرب كتابة جملة من عندك هنا
test_sentence = "توقعات بمنخفض جوي قادم من البحر المتوسط"
print(f"النص: {test_sentence}")
print(f"التصنيف المتوقع: {predict(test_sentence)}")

from transformers import TrainingArguments, Trainer

# 1. إعدادات التدريب
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=20,
    per_device_train_batch_size=4,
    logging_steps=5,                # قللنا الرقم لنرى التحديثات بسرعة أكبر
    eval_strategy="epoch"
)

# 2. إنشاء المدرب (Trainer) مع تحديد الأقسام بدقة
trainer = Trainer(
    model=model,
    args=training_args,
    # هنا التعديل: حددنا قسم التدريب والاختبار من القاموس
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"]
)

# 3. ابدأ التدريب
print("بدء عملية التدريب... يرجى الانتظار")
trainer.train()
print("تم التدريب بنجاح!")

import torch

def predict_final(text):
    # تحضير النص
    text_preprocessed = prep_object.preprocess(text)
    inputs = tokenizer(text_preprocessed, return_tensors="pt", padding=True, truncation=True, max_length=128)

    # نقل البيانات للمعالج (GPU إذا كان متاحاً)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    model.eval() # وضع النموذج في نمط التقييم
    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    target_class = torch.argmax(probs).item()

    labels = ["سياسة", "اقتصاد", "رياضة", "طقس"]
    return labels[target_class]

# اختبار حقيقي الآن
test_list = [
    "فوز ساحق للمنتخب في كأس آسيا",
    "انخفاض سعر صرف الريال مقابل العملات الأجنبية",
    "عاصفة ثلجية مرتقبة تضرب العاصمة"
]

for t in test_list:
    print(f"النص: {t} -> التصنيف: {predict_final(t)}")

import torch

def predict_news_category(text):
    # 1. تنظيف النص العربي بنفس الطريقة التي تدرب عليها النموذج
    text_preprocessed = prep_object.preprocess(text)

    # 2. تحويل النص إلى أرقام (Tokens) ونقلها إلى GPU
    inputs = tokenizer(text_preprocessed, return_tensors="pt", padding=True, truncation=True, max_length=128)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # 3. وضع النموذج في نمط التوقع (Evaluation Mode)
    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)

    # 4. استخراج الفئة الأعلى احتمالاً
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    target_class = torch.argmax(probs).item()

    # ترتيب التصنيفات كما وضعناها في الداتا
    labels = ["سياسة", "اقتصاد", "رياضة", "طقس"]
    return labels[target_class], probs[0][target_class].item()

# --- جرب النموذج هنا بجمل من اختيارك ---
test_sentences = [
    "انخفاض حاد في أسعار صرف العملات الرقمية هذا الصباح",
    "توقعات بهبوب رياح قوية وموجة غبار على المناطق الوسطى",
    "اجتماع وزراء الخارجية العرب لمناقشة ملف السلام",
    "تأهل الفريق إلى دور نصف النهائي بعد مباراة حماسية"
]

print("-" * 30)
for sentence in test_sentences:
    category, confidence = predict_news_category(sentence)
    print(f"النص: {sentence}")
    print(f"التصنيف: {category} (نسبة الثقة: {confidence*100:.2f}%)")
    print("-" * 30)